name: "Append on Merge"
description: "Github Action to combine files while preventing PR conflicts"
inputs:
  github_token:
    description: "Github Token"
    required: true
  mode:
    description: "preview: Post preview as pull request comment, commit: Commit & Push"
    required: false
    default: "preview"
  input_path:
    description: "input_path"
    required: false
    default: "input"
  base:
    description: "base"
    required: false
    default: "README.md"
  output:
    description: "output"
    required: false
    default: "README.md"
  processed_path:
    description: "processed_path"
    required: false
    default: "processed"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    # Change path, run the code
    # - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    #   shell: bash
    - shell: bash
      run: ruby ${{ github.action_path }}/append_on_merge.rb "${{ inputs.input_path }}" "${{ inputs.base }}" "${{ inputs.output }}" "${{ inputs.processed_path }}"

    # See diff & output diff for comment
    - id: diff
      shell: bash
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

        eof="EOF$RANDOM$(date +%s)"

        echo "git_diff<<$eof" >> $GITHUB_OUTPUT
        git diff >> $GITHUB_OUTPUT
        echo "$eof" >> $GITHUB_OUTPUT

    - name: Add preview comment
      uses: marocchino/sticky-pull-request-comment@v2.2.1
      if: ${{ inputs.mode == 'preview' }}
      with:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          Changes when this Pull Request is merged:
          ```diff
          ${{ steps.diff.outputs.git_diff }}
          ```

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      if: ${{ inputs.mode == 'commit' }}
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
