name: "Merge on Merge"
description: "Github Action to combine JSON files while preventing PR conflicts"
inputs:
  github_token:
    description: "Github Token"
    default: "${{ github.token }}"
    required: false
  mode:
    description: "preview: Post preview as pull request comment, commit: Commit & Push"
    required: false
    default: "preview"
  input_path:
    description: "JSON input folder"
    required: false
    default: "input"
  base:
    description: "base"
    required: false
    default: "out.json"
  merge_json_path:
    description: "JSON traverse path to merge the input in, use dot notation"
    required: false
    default: "json.path.to.merge"
  output:
    description: "output"
    required: false
    default: "out.json"
  processed_path:
    description: "processed_path"
    required: false
    default: "processed"
  repo:
    description: "repo"
    required: false

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - shell: bash
      run: ruby ${{ github.action_path }}/merge_on_merge.rb "${{ inputs.input_path }}" "${{ inputs.base }}" "${{ inputs.merge_json_path }}" "${{ inputs.output }}" "${{ inputs.processed_path }}"

    # See diff & output diff for comment
    - id: diff
      shell: bash
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

        eof="EOF$RANDOM$(date +%s)"

        echo "git_diff<<$eof" >> $GITHUB_OUTPUT
        git diff >> $GITHUB_OUTPUT
        echo "$eof" >> $GITHUB_OUTPUT

    - name: Add preview comment
      uses: marocchino/sticky-pull-request-comment@v2.2.1
      if: ${{ inputs.mode == 'preview' }}
      with:
        # GITHUB_TOKEN: ${{ inputs.github_token }}
        repo: ${{ inputs.repo }}
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          Changes when this Pull Request is merged:
          ```diff
          ${{ steps.diff.outputs.git_diff }}
          ```

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      if: ${{ inputs.mode == 'commit' }}
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
