name: "Append on Merge"
description: "Github Action to combine files while preventing PR conflicts"
inputs:
  github_token:
    description: "Github Token"
    required: true
  mode:
    description: "preview: Post preview as pull request comment, commit: Commit & Push"
    required: false
    default: "preview"

runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    # Runs the code
    - run: ruby append_on_merge.rb
      shell: bash

    # See diff & output diff for comment
    - id: diff
      shell: bash
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

        eof="EOF$RANDOM$(date +%s)"

        echo "git_diff<<$eof" >> $GITHUB_OUTPUT
        git diff >> $GITHUB_OUTPUT
        echo "$eof" >> $GITHUB_OUTPUT

    # TODO: Replace with newer/faster action
    - uses: mb2dev/github-action-comment-pull-request@1.0.0
      if: ${{ inputs.mode == 'preview' }}
      with:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        message: |
          Changes when this Pull Request is merged:
          ```diff
          ${{ steps.diff.outputs.git_diff }}
          ```

    # Commit on merge
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      if: ${{ inputs.mode == 'commit' }}
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ github.ref }}
