name: "Append on Merge"
description: "Github Action to combine files while preventing PR conflicts"
inputs:
  github_token:
    description: "Github Token"
    required: true
  branch:
    description: "Branch to push"
    required: false
    default: "main"
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1

    # Runs the code
    - run: ruby append_on_merge.rb
      shell: bash

    # See diff
    - run: git diff
      shell: bash

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ inputs.github_token }}
        branch: ${{ inputs.branch }}
