name: Demo

on:
  pull_request:
  push:
    branches: [ main ]
#   schedule:
#     - cron: "0 0 * * *"
  workflow_dispatch:
#   watch:
#     types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: narze/append_on_merge@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          preview: true
          commit: false

      - uses: narze/append_on_merge@main
        if: ${{ github.event_name == 'push' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          preview: false
          commit: true
