name: Demo

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: narze/append_on_merge@main
        if: ${{ github.event_name == 'pull_request' }}
        with:
          mode: "preview"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_path: "input"
          base: "README.md"
          output: "README.md"
          processed_path: "processed"

      - uses: narze/append_on_merge@main
        if: ${{ github.event_name == 'push' }}
        with:
          mode: "commit"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          input_path: "input"
          base: "README.md"
          output: "README.md"
          processed_path: "processed"
